### ISSUE TITLE
validación en el campo de contraseña para registrar un usuario

### ISSUE THREAD

**Issue by emiarias** [franad23/FrontendProyFinal#1]
**Proceso**
Al ingresar al formulario de registro

**Resultado esperado**
ingresar los datos del formulario y proceder al registro del usuario
El campo del título de la encuesta deja ingresar demasiados caracteres

**Resultado actual**
Al ingresar la contraseña, se visualiza el mensaje de "la contraseña no cumple con los requisitos" pero no se visualiza cuales son los requisitos (cantidad de caracteres, algún caracter especial o numeros)

**Captura**

![image](https://github.com/franad23/FrontendProyFinal/assets/18445151/c49cf534-3702-439f-87f8-ca3a38529fa5)

**Comment by franad23** [comment]
En el icono i estan los req de la contraseña. Corregido
