### ISSUE TITLE
Quitar los mensajes en la consola

### ISSUE THREAD

**Issue by emiarias** [franad23/FrontendProyFinal#2]
**Proceso**
Al iniciar sesión

**Resultado esperado**
se visualiza la pagina principal

**Resultado actual**
Se visualiza la pagina principal, pero se ve mensajes en la consola. Eliminar todos los console.log del proyecto

**Captura**
![image](https://github.com/franad23/FrontendProyFinal/assets/18445151/3ca8827f-e2c5-42ab-8ea6-c3b8e2d47d0f)

**Comment by franad23** [comment]
Corregido
