### ISSUE TITLE
Error en el link para compartir el formulario creado

### ISSUE THREAD

**Issue by emiarias** [franad23/FrontendProyFinal#3]
**Proceso**
Al crear una encuesta y seleccionar el link para compartirla

**Resultado esperado**
Poder utilizar la encuesta

**Resultado actual**
El enlace del formulario no funciona, verificar el mismo ya que comienza con localhost:5173

**Captura**
![image](https://github.com/franad23/FrontendProyFinal/assets/18445151/d55cc239-e16f-4693-b27f-d0b5e9f526f5)

**Comment by franad23** [comment]
Corregido
