### ISSUE TITLE
Error al visualizar los datos de una encuesta

### ISSUE THREAD

**Issue by emiarias** [franad23/FrontendProyFinal#4]
**Proceso**
Cuando ingresamos en una encuesta creada

**Resultado esperado**
visualizar correctamente los datos de la encuesta, verificar en todos los tamaños de dispositivos

**Resultado actual**
Al ingresar la totalidad de los datos permitidos en los titulos, la encuesta no se muestra correctamente.

**Captura**
![image](https://github.com/franad23/FrontendProyFinal/assets/18445151/a1948229-af18-471c-8102-a372f9f0df45)

![image](https://github.com/franad23/FrontendProyFinal/assets/18445151/ef7df18f-4679-487d-be55-d3cbee439525)

![image](https://github.com/franad23/FrontendProyFinal/assets/18445151/d738915c-1538-4c81-85c8-4b5f1e1cedef)

**Comment by franad23** [comment]
Corregido

**Comment by emiarias** [comment]
@franad23 esta corregido el titulo de la encuesta, pero no las preguntas cuando la cantidad de caracteres excede el ancho del contenedor. Por lo tanto esta issue sigue abierta para corregir

![image](https://github.com/franad23/FrontendProyFinal/assets/18445151/a14ac791-b247-4068-af73-084451190b48)
