### ISSUE TITLE
Corregir la interfaz de la pagina principal para dispositivos pequeños

### ISSUE THREAD

**Issue by emiarias** [franad23/FrontendProyFinal#5]
**Proceso**
Al iniciar sesion en un celuar

**Resultado esperado**
visualizar las encuestas de forma correcta

**Resultado actual**
El sitio no es responsive, verificar las encuestas iniciales

**Captura**
![image](https://github.com/franad23/FrontendProyFinal/assets/18445151/7c1b7c9e-0537-46db-9c60-7f45cde89d81)

**Comment by franad23** [comment]
Corregido
